In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Movie+Assignment+Data.csv')

In [3]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

# ANALYSING THE DATA

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5031 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [5]:
df.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [7]:
df.shape

(5043, 28)

In [8]:
round(100*(df.isnull().sum()/len(df.index)),2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

In [9]:
df = df[~df.gross.isnull()]
df = df[~df.aspect_ratio.isnull()]
df = df[~df.plot_keywords.isnull()]

In [10]:
df.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4031.000000,4030.000000,4028.000000,4022.000000,4029.000000,4.031000e+03,4.031000e+03,4031.000000,4024.000000,4031.000000,3.797000e+03,4028.000000,4028.00000,4031.000000,4031.000000,4031.000000
mean,163.340858,109.857072,769.637041,739.084038,7488.253165,4.992915e+07,1.004799e+05,11106.532622,1.367296,321.817415,4.601506e+07,2003.116435,1932.65144,6.477524,2.105674,8973.269660
std,122.186137,22.741240,2990.038452,1835.862627,15176.158266,6.901740e+07,1.486017e+05,18686.120706,2.034938,402.405471,2.248540e+08,9.981438,4424.65625,1.050821,0.350145,21060.087765
min,1.000000,37.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1920.000000,0.00000,1.600000,1.180000,0.000000
25%,75.000000,95.000000,10.000000,179.000000,723.000000,6.395684e+06,1.714650e+04,1799.000000,0.000000,100.000000,1.000000e+07,1999.000000,361.50000,5.900000,1.850000,0.000000
50%,134.000000,106.000000,60.000000,424.000000,1000.000000,2.687082e+07,4.931200e+04,3850.000000,1.000000,199.000000,2.500000e+07,2005.000000,660.00000,6.600000,2.350000,204.000000
75%,220.000000,120.000000,230.000000,681.000000,12000.000000,6.424701e+07,1.191815e+05,15815.500000,2.000000,383.000000,5.000000e+07,2010.000000,968.00000,7.200000,2.350000,11000.000000
max,813.000000,334.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.00000,9.300000,16.000000,349000.000000

Now before we start cleaning the dataset further , lets remove the unwanted columns

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4031 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      4029 non-null   object
 1   director_name              4028 non-null   object
 2   num_critic_for_reviews     4031 non-null   float64
 3   duration                   4030 non-null   float64
 4   director_facebook_likes    4028 non-null   float64
 5   actor_3_facebook_likes     4022 non-null   float64
 6   actor_2_name               4028 non-null   object
 7   actor_1_facebook_likes     4029 non-null   float64
 8   gross                      4031 non-null   float64
 9   genres                     4031 non-null   object
 10  actor_1_name               4029 non-null   object
 11  movie_title                4031 non-null   object
 12  num_voted_users            4031 non-null   int64
 13  cast_total_facebook_likes  4031 non-null   int64
 14  actor_3_name               4022 non-null   object
 15  facenumber_in_poster       4024 non-null   float64
 16  plot_keywords              4031 non-null   object
 17  movie_imdb_link            4031 non-null   object
 18  num_user_for_reviews       4031 non-null   float64
 19  language                   4029 non-null   object
 20  country                    4031 non-null   object
 21  content_rating             3994 non-null   object
 22  budget                     3797 non-null   float64
 23  title_year                 4028 non-null   float64
 24  actor_2_facebook_likes     4028 non-null   float64
 25  imdb_score                 4031 non-null   float64
 26  aspect_ratio               4031 non-null   float64
 27  movie_facebook_likes       4031 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 913.3+ KB

In [12]:
df.language.isnull().sum()

2

In [13]:
df['language'].fillna('English' , inplace = True)

In [14]:
df.language.isnull().sum()

0

In [15]:
df.shape

(4031, 28)

In [16]:
df =  df.assign(GrossM = lambda x : x.gross/1000000)
df =  df.assign(BudgetM = lambda x : x.budget/1000000)

In [17]:
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,GrossM,BudgetM
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,760.505847,237.0000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,309.404152,300.0000
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,200.074175,245.0000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,448.130642,250.0000
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000,73.058679,263.7000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697,0.673780,0.0100
5029,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817,0.094596,1.0000
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000,0.424760,0.0070
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,USA,R,7000.0,1992.0,20.0,6.9,1.37,0,2.040920,0.0070
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,0.085222,0.0011

In [18]:
df['profit'] = df['gross'] - df['budget']

In [19]:
df['profit']

0       523505847.0
1         9404152.0
2       -44925825.0
3       198130642.0
5      -190641321.0
           ...
5027       663780.0
5029      -905404.0
5033       417760.0
5035      2033920.0
5042        84122.0
Name: profit, Length: 4031, dtype: float64

In [20]:
df.sort_values('profit' , ascending = False)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,GrossM,BudgetM,profit
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,760.505847,237.0,523505847.0
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000,652.177271,150.0,502177271.0
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000,658.672302,200.0,458672302.0
3024,Color,George Lucas,282.0,125.0,0.0,504.0,Peter Cushing,11000.0,460935665.0,Action|Adventure|Fantasy|Sci-Fi,...,PG,11000000.0,1977.0,1000.0,8.7,2.35,33000,460.935665,11.0,449935665.0
3080,Color,Steven Spielberg,215.0,120.0,14000.0,548.0,Dee Wallace,861.0,434949459.0,Family|Sci-Fi,...,PG,10500000.0,1982.0,725.0,7.9,1.85,34000,434.949459,10.5,424449459.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4909,Color,Jay Duplass,93.0,84.0,157.0,98.0,Jennifer Lafleur,962.0,140016.0,Comedy|Drama|Horror|Romance,...,R,NaN,2008.0,873.0,6.0,1.85,443,0.140016,NaN,NaN
4913,Color,Marianna Palka,38.0,86.0,123.0,782.0,Martin Starr,3000.0,15542.0,Comedy|Drama|Romance,...,R,NaN,2008.0,985.0,6.5,1.85,0,0.015542,NaN,NaN
4944,Color,Zal Batmanglij,136.0,85.0,129.0,100.0,James Urbaniak,120.0,405614.0,Drama|Mystery|Sci-Fi|Thriller,...,R,NaN,2011.0,119.0,6.7,1.85,0,0.405614,NaN,NaN
4960,Color,Peter Chelsom,57.0,100.0,23.0,545.0,Elden Henson,1000.0,2643689.0,Comedy|Drama,...,PG-13,NaN,1998.0,577.0,7.3,1.85,0,2.643689,NaN,NaN
5001,Color,Martin Scorsese,71.0,117.0,17000.0,476.0,Levon Helm,725.0,321952.0,Documentary|Music,...,PG,NaN,1978.0,572.0,8.2,1.85,0,0.321952,NaN,NaN

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4031 entries, 0 to 5042
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      4029 non-null   object
 1   director_name              4028 non-null   object
 2   num_critic_for_reviews     4031 non-null   float64
 3   duration                   4030 non-null   float64
 4   director_facebook_likes    4028 non-null   float64
 5   actor_3_facebook_likes     4022 non-null   float64
 6   actor_2_name               4028 non-null   object
 7   actor_1_facebook_likes     4029 non-null   float64
 8   gross                      4031 non-null   float64
 9   genres                     4031 non-null   object
 10  actor_1_name               4029 non-null   object
 11  movie_title                4031 non-null   object
 12  num_voted_users            4031 non-null   int64
 13  cast_total_facebook_likes  4031 non-null   int64
 14  actor_3_name               4022 non-null   object
 15  facenumber_in_poster       4024 non-null   float64
 16  plot_keywords              4031 non-null   object
 17  movie_imdb_link            4031 non-null   object
 18  num_user_for_reviews       4031 non-null   float64
 19  language                   4031 non-null   object
 20  country                    4031 non-null   object
 21  content_rating             3994 non-null   object
 22  budget                     3797 non-null   float64
 23  title_year                 4028 non-null   float64
 24  actor_2_facebook_likes     4028 non-null   float64
 25  imdb_score                 4031 non-null   float64
 26  aspect_ratio               4031 non-null   float64
 27  movie_facebook_likes       4031 non-null   int64
 28  GrossM                     4031 non-null   float64
 29  BudgetM                    3797 non-null   float64
 30  profit                     3797 non-null   float64
dtypes: float64(16), int64(3), object(12)
memory usage: 1007.8+ KB

In [24]:
movies = df.drop('content_rating' , axis=1)
movies = df.drop('movie_imdb_link' , axis=1)
movies = df.drop('aspect_ratio' , axis=1)
movies = df.drop('movie_facebook_likes' , axis=1)
movies = df.drop('cast_total_facebook_likes' , axis=1)
movies = df.drop('facenumber_in_poster' , axis=1)
movies = df.drop('title_year' , axis=1)
movies = df.drop('country' , axis=1)
movies = df.drop('plot_keywords' , axis=1)
movies = df.drop('director_facebook_likes' , axis=1)
movies = df.drop('actor_3_facebook_likes' , axis=1)
movies = df.drop('actor_1_facebook_likes' , axis=1)
movies = df.drop('actor_2_facebook_likes' , axis=1)
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,country,content_rating,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes,GrossM,BudgetM,profit
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,USA,PG-13,237000000.0,2009.0,7.9,1.78,33000,760.505847,237.0000,523505847.0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,USA,PG-13,300000000.0,2007.0,7.1,2.35,0,309.404152,300.0000,9404152.0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,UK,PG-13,245000000.0,2015.0,6.8,2.35,85000,200.074175,245.0000,-44925825.0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,USA,PG-13,250000000.0,2012.0,8.5,2.35,164000,448.130642,250.0000,198130642.0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,USA,PG-13,263700000.0,2012.0,6.6,2.35,24000,73.058679,263.7000,-190641321.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,Iran,Not Rated,10000.0,2000.0,7.5,1.85,697,0.673780,0.0100,663780.0
5029,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,Japan,NaN,1000000.0,1997.0,7.4,1.85,817,0.094596,1.0000,-905404.0
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,USA,PG-13,7000.0,2004.0,7.0,1.85,19000,0.424760,0.0070,417760.0
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,USA,R,7000.0,1992.0,6.9,1.37,0,2.040920,0.0070,2033920.0
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,USA,PG,1100.0,2004.0,6.6,1.85,456,0.085222,0.0011,84122.0

In [25]:
Top_10_Movies = movies.head(10)
Top_10_Movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,country,content_rating,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes,GrossM,BudgetM,profit
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,USA,PG-13,237000000.0,2009.0,7.9,1.78,33000,760.505847,237.0,523505847.0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,USA,PG-13,300000000.0,2007.0,7.1,2.35,0,309.404152,300.0,9404152.0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,UK,PG-13,245000000.0,2015.0,6.8,2.35,85000,200.074175,245.0,-44925825.0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,USA,PG-13,250000000.0,2012.0,8.5,2.35,164000,448.130642,250.0,198130642.0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,USA,PG-13,263700000.0,2012.0,6.6,2.35,24000,73.058679,263.7,-190641321.0
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,USA,PG-13,258000000.0,2007.0,6.2,2.35,0,336.530303,258.0,78530303.0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,USA,PG,260000000.0,2010.0,7.8,1.85,29000,200.807262,260.0,-59192738.0
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,USA,PG-13,250000000.0,2015.0,7.5,2.35,118000,458.991599,250.0,208991599.0
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,UK,PG,250000000.0,2009.0,7.5,2.35,10000,301.956980,250.0,51956980.0
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,USA,PG-13,250000000.0,2016.0,6.9,2.35,197000,330.249062,250.0,80249062.0

In [26]:
display(Top_10_Movies.drop_duplicates())

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,country,content_rating,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes,GrossM,BudgetM,profit
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,USA,PG-13,237000000.0,2009.0,7.9,1.78,33000,760.505847,237.0,523505847.0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,USA,PG-13,300000000.0,2007.0,7.1,2.35,0,309.404152,300.0,9404152.0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,UK,PG-13,245000000.0,2015.0,6.8,2.35,85000,200.074175,245.0,-44925825.0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,USA,PG-13,250000000.0,2012.0,8.5,2.35,164000,448.130642,250.0,198130642.0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,USA,PG-13,263700000.0,2012.0,6.6,2.35,24000,73.058679,263.7,-190641321.0
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,USA,PG-13,258000000.0,2007.0,6.2,2.35,0,336.530303,258.0,78530303.0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,USA,PG,260000000.0,2010.0,7.8,1.85,29000,200.807262,260.0,-59192738.0
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,USA,PG-13,250000000.0,2015.0,7.5,2.35,118000,458.991599,250.0,208991599.0
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,UK,PG,250000000.0,2009.0,7.5,2.35,10000,301.956980,250.0,51956980.0
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,USA,PG-13,250000000.0,2016.0,6.9,2.35,197000,330.249062,250.0,80249062.0

In [28]:
IMDb_Top_250 = df.sort_values('imdb_score' , ascending = False)
IMDb_Top_250 = IMDb_Top_250[IMDb_Top_250.num_voted_users > 25000]
IMDb_Top_250 = IMDb_Top_250.head(250)
IMDb_Top_250['Rank'] = range(1,251)
IMDb_Top_250

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,GrossM,BudgetM,profit,Rank
1937,Color,Frank Darabont,199.0,142.0,0.0,461.0,Jeffrey DeMunn,11000.0,28341469.0,Crime|Drama,...,25000000.0,1994.0,745.0,9.3,1.85,108000,28.341469,25.0,3341469.0,1
3466,Color,Francis Ford Coppola,208.0,175.0,0.0,3000.0,Marlon Brando,14000.0,134821952.0,Crime|Drama,...,6000000.0,1972.0,10000.0,9.2,1.85,43000,134.821952,6.0,128821952.0,2
2837,Color,Francis Ford Coppola,149.0,220.0,0.0,3000.0,Al Pacino,22000.0,57300000.0,Crime|Drama,...,13000000.0,1974.0,14000.0,9.0,1.85,14000,57.300000,13.0,44300000.0,3
66,Color,Christopher Nolan,645.0,152.0,22000.0,11000.0,Heath Ledger,23000.0,533316061.0,Action|Crime|Drama|Thriller,...,185000000.0,2008.0,13000.0,9.0,2.35,37000,533.316061,185.0,348316061.0,4
339,Color,Peter Jackson,328.0,192.0,0.0,416.0,Billy Boyd,5000.0,377019252.0,Action|Adventure|Drama|Fantasy,...,94000000.0,2003.0,857.0,8.9,2.35,16000,377.019252,94.0,283019252.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4415,Color,Fabián Bielinsky,94.0,114.0,44.0,7.0,Gastón Pauls,827.0,1221261.0,Crime|Drama|Thriller,...,1500000.0,2000.0,22.0,7.9,1.85,0,1.221261,1.5,-278739.0,246
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,237000000.0,2009.0,936.0,7.9,1.78,33000,760.505847,237.0,523505847.0,247
1871,Color,Pierre Morel,309.0,93.0,180.0,485.0,Holly Valance,14000.0,145000989.0,Action|Thriller,...,25000000.0,2008.0,816.0,7.9,2.35,29000,145.000989,25.0,120000989.0,248
1993,Color,Roger Donaldson,126.0,127.0,79.0,50.0,Antony Starr,12000.0,5128124.0,Biography|Drama|Sport,...,25000000.0,2005.0,506.0,7.9,2.35,11000,5.128124,25.0,-19871876.0,249
162,Color,Dean DeBlois,292.0,102.0,255.0,953.0,Djimon Hounsou,18000.0,176997107.0,Action|Adventure|Animation|Comedy|Family|Fantasy,...,145000000.0,2014.0,3000.0,7.9,2.35,46000,176.997107,145.0,31997107.0,250

In [31]:
IMDb_Top_250['language']

1937    English
3466    English
2837    English
66      English
339     English
         ...
4415    Spanish
0       English
1871    English
1993    English
162     English
Name: language, Length: 250, dtype: object

In [37]:
Top_Foreign_Lang_Film = IMDb_Top_250.loc[~(IMDb_Top_250.language == 'English')]

In [69]:
Top_10_Director=movies.sort_values("director_name")
Top_10_Director=Top_10_Director.groupby('director_name').imdb_score.mean()
Top_10_Director

director_name
Aaron Schneider       7.100
Aaron Seltzer         2.700
Abel Ferrara          6.600
Adam Brooks           7.200
Adam Goldberg         5.400
                      ...
Zack Snyder           7.175
Zak Penn              6.600
Zal Batmanglij        6.800
Álex de la Iglesia    6.100
Émile Gaudreault      6.700
Name: imdb_score, Length: 1789, dtype: float64

In [72]:
Top_10_Director=Top_10_Director.nlargest(10)
Top_10_Director=pd.DataFrame(Top_10_Director)
Top_10_Director

                   imdb_score
director_name
Charles Chaplin      8.600000
Tony Kaye            8.600000
Alfred Hitchcock     8.500000
Damien Chazelle      8.500000
Majid Majidi         8.500000
Ron Fricke           8.500000
Sergio Leone         8.433333
Christopher Nolan    8.425000
Asghar Farhadi       8.400000
Catherine Owens      8.400000

In [74]:
df.genres.value_counts()

Drama                                  169
Comedy|Drama|Romance                   162
Comedy                                 158
Comedy|Drama                           156
Comedy|Romance                         135
                                      ...
Fantasy|Horror|Romance                   1
Adventure|Comedy|Sci-Fi|Western          1
Action|Biography|Drama|Thriller|War      1
Action|Fantasy|Western                   1
Comedy|Crime|Horror                      1
Name: genres, Length: 777, dtype: int64

In [75]:
df[["genre_1","genre_2","to be dropped"]]=movies.genres.str.split('|',2,expand=True)
df[['movie_title','genres',"genre_1","genre_2","to be dropped"]]

,movie_title,genres,genre_1,genre_2,to be dropped
0,Avatar,Action|Adventure|Fantasy|Sci-Fi,Action,Adventure,Fantasy|Sci-Fi
1,Pirates of the Caribbean: At World's End,Action|Adventure|Fantasy,Action,Adventure,Fantasy
2,Spectre,Action|Adventure|Thriller,Action,Adventure,Thriller
3,The Dark Knight Rises,Action|Thriller,Action,Thriller,None
5,John Carter,Action|Adventure|Sci-Fi,Action,Adventure,Sci-Fi
...,...,...,...,...,...
5027,The Circle,Drama,Drama,None,None
5029,The Cure,Crime|Horror|Mystery|Thriller,Crime,Horror,Mystery|Thriller
5033,Primer,Drama|Sci-Fi|Thriller,Drama,Sci-Fi,Thriller
5035,El Mariachi,Action|Crime|Drama|Romance|Thriller,Action,Crime,Drama|Romance|Thriller
5042,My Date with Drew,Documentary,Documentary,None,None

In [79]:
df.drop('to be dropped' ,axis = 1)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,GrossM,BudgetM,profit,genre_1,genre_2
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,2009.0,936.0,7.9,1.78,33000,760.505847,237.0000,523505847.0,Action,Adventure
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,2007.0,5000.0,7.1,2.35,0,309.404152,300.0000,9404152.0,Action,Adventure
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,2015.0,393.0,6.8,2.35,85000,200.074175,245.0000,-44925825.0,Action,Adventure
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2012.0,23000.0,8.5,2.35,164000,448.130642,250.0000,198130642.0,Action,Thriller
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,2012.0,632.0,6.6,2.35,24000,73.058679,263.7000,-190641321.0,Action,Adventure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,2000.0,0.0,7.5,1.85,697,0.673780,0.0100,663780.0,Drama,None
5029,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,1997.0,13.0,7.4,1.85,817,0.094596,1.0000,-905404.0,Crime,Horror
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,2004.0,45.0,7.0,1.85,19000,0.424760,0.0070,417760.0,Drama,Sci-Fi
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,1992.0,20.0,6.9,1.37,0,2.040920,0.0070,2033920.0,Action,Crime
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,2004.0,23.0,6.6,1.85,456,0.085222,0.0011,84122.0,Documentary,None

In [81]:
df.genre_2.fillna(df.genre_1 , inplace = True)
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,GrossM,BudgetM,profit,genre_1,genre_2,to be dropped
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,936.0,7.9,1.78,33000,760.505847,237.0000,523505847.0,Action,Adventure,Fantasy|Sci-Fi
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,5000.0,7.1,2.35,0,309.404152,300.0000,9404152.0,Action,Adventure,Fantasy
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,393.0,6.8,2.35,85000,200.074175,245.0000,-44925825.0,Action,Adventure,Thriller
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,23000.0,8.5,2.35,164000,448.130642,250.0000,198130642.0,Action,Thriller,None
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,632.0,6.6,2.35,24000,73.058679,263.7000,-190641321.0,Action,Adventure,Sci-Fi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,0.0,7.5,1.85,697,0.673780,0.0100,663780.0,Drama,Drama,None
5029,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,13.0,7.4,1.85,817,0.094596,1.0000,-905404.0,Crime,Horror,Mystery|Thriller
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,45.0,7.0,1.85,19000,0.424760,0.0070,417760.0,Drama,Sci-Fi,Thriller
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,20.0,6.9,1.37,0,2.040920,0.0070,2033920.0,Action,Crime,Drama|Romance|Thriller
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,23.0,6.6,1.85,456,0.085222,0.0011,84122.0,Documentary,Documentary,None

In [83]:
df.shape

(4031, 34)

In [85]:
PopGenre = df.sort_values(by='gross' , ascending = False)
PopGenre = df.groupby('genres').gross.mean()
PopGenre = PopGenre.nlargest(5)
PopGenre = pd.DataFrame(PopGenre)
PopGenre

                                                        gross
genres
Family|Sci-Fi                                    4.349495e+08
Adventure|Animation|Drama|Family|Musical         4.227838e+08
Adventure|Animation|Comedy|Drama|Family|Fantasy  3.564544e+08
Action|Biography|Drama|History|Thriller|War      3.501236e+08
Action|Adventure|Fantasy|Sci-Fi                  2.966848e+08

In [90]:
Meryl_Streep = df.loc[df.actor_1_name == 'Meryl Streep']
Leo_Caprio = df.loc[df.actor_1_name == 'Leonardo DiCaprio']
Brad_Pitt = df.loc[df.actor_1_name == 'Brad Pitt']
Combined = pd.concat([Meryl_Streep , Leo_Caprio , Brad_Pitt])
Combined = Combined.groupby(by='actor_1_name')
Combined.num_critic_for_reviews.mean()

actor_1_name
Brad Pitt            245.000000
Leonardo DiCaprio    330.190476
Meryl Streep         181.454545
Name: num_critic_for_reviews, dtype: float64

In [91]:
Combined.num_user_for_reviews.mean()

actor_1_name
Brad Pitt            742.352941
Leonardo DiCaprio    914.476190
Meryl Streep         297.181818
Name: num_user_for_reviews, dtype: float64

FROM THE ABOVE INFO WE CAN TELL THAT LEONARDO HAS THE HIGHEST OUT OF THESE ACTORS